# -*- coding: utf-8 -*-
"""6-1-2025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C5nIKfJemuhKxhyZjiipYoUJAR5N3bIZ
"""

my_list = [1, "hello", 3.14, True]
print("original list:",my_list)
#adding element to a list
my_list.append("world")
print("list after appending world:",my_list)
#removing a element from list
my_list.remove(3.14)
print('list after removing 3.14:',my_list)

my_tuple = (1, "hello", 3.14, True)
print("Original tuple:", my_tuple)

# Accessing elements in a tuple
print("First element:", my_tuple[0])
print("Second element:", my_tuple[1])
print("Last element:", my_tuple[-1])

for i in range(1,6):
  print(i)

i = 1
while i <= 5:
  print(i)
  i += 1



number = int(input("Enter a number: "))

if number > 0:
  print("Positive number")
elif number < 0:
  print("Negative number")
else:
  print("Zero")