# -*- coding: utf-8 -*-
"""7-1-25

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w5faVhUWuREDkXXnyPW5egzpUxxQpSlm
"""

print(dir(str))

#uppercase
a="reddy"
b=a.upper()
print(b)

#count
a="reddy"
b=a.count(a)
print(b)

#replace
a="reddy"
b=a.replace("reddy","srikar")
print(b)

functions can be called independently methods uses dot notation

a=range(7)
b=list(a)
print(b)

#adding two numbers
def add_numbers(x, y):
  result=x + y
  return result
print(add_numbers(5, 3))

#function with default
def greet(name="hello"):
  print(name)
greet()

def calculate_sum(*args):
  total = sum(args)
  return total
print("sum of 1,2,3:", calculate_sum(1,2,3))
print("sum of 1,2,3,4:", calculate_sum(1,2,3,4))

username = "admin"
password = "1234"

while True:
  input_username = input("Enter username: ")
  input_password = input("Enter password: ")

  if input_username == username and input_password == password:
    print("Login successful!")
    break
  else:
    print("Login failed. Please try again.")

#length
my_list = [1, 2, 3, 4, 5]
list_length = len(my_list)
print(f"The length of the list is: {list_length}")

#sum
numbers = [10, 20, 30, 40, 50]
total_sum = sum(numbers)
print(f"The sum of the numbers in the list is: {total_sum}")

def multiply(a,b):
  return a*b
print(multiply(7,7))

