# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJtreCEbYORTUjdij4VrNesaZqOdc33V
"""

list = ['apple','banana','cherry']
print(list)

list = ['apple','banana','cherry']
list.sort()

a = [1, 2, 3]
b = [4, 5, 6]
c=a+b
print(c)

a = [1, 2, 3,4,5]
a[1:3]



a[:4]

